---
version: '3.7'
services:
    nginx:
      image: nginx:alpine
      ports: 
      - target: 80
        published: 80
        protocol: tcp 
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      depends_on: 
      - server
      - client
      - mongo
      


    server:
      image: jenkinsdockertest:5000/server      
      build: ./server
      
      
       

    client:
      image: jenkinsdockertest:5000/client
      build: ./client
            
    
      environment:
      - REACT_APP_SERVICE_HOST=${REACT_APP_SERVICE_HOST}
    

    mongo:
      image: mongo:latest
      
      
      
    

    mongo-seed:
      image: fvilers/mongo-seed:1.0.0
      environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      volumes:
      - ./data:/data
      command:
      - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"

...

